KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/Index.cshtml.cs
using KuberMICManager.Core.Domain.Entities;
using KuberMICManager.Core.Domain.Entities.Identity;
using KuberMICManager.Core.Domain.Interfaces;
using KuberMICManager.Core.Domain.Interfaces.Services;
using KuberMICManager.Core.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using SautinSoft;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static KuberMICManager.Core.Domain.Entities.Application.Common;

namespace KuberMICManager.Client.WebUI.Pages.Loans
{
    [Authorize(Policy = "CanViewLoans")]
    public class IndexModel : PageModel
    {
        private readonly ILoanService _loanService;
        private readonly ILoanUnitOfWork _loanUnitOfWork;
        private readonly IUserLogRepository _userLogRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public IEnumerable<LoanIndexModel> Loans { get; set; }

        public List<LoanSearchEnumModel> CheckBoxLoanSearchGroup { get; set; }
        public string SearchFor { get; set; }
        public LoanFilterType? FilterType { get; set; }
        public DateTime? EndDate { get; set; }
        public string AtRiskBeaconScoreThreshold { get; set; }
        public string AtRiskLTVThreshold { get; set; }

        public IndexModel(ILoanService loanService,
                          ILoanUnitOfWork loanUnitOfWork,
                          IUserLogRepository userLogRepository,
                          UserManager<ApplicationUser> userManager,
                          IMemoryCache cache)
        {
            _loanService = loanService;
            _loanUnitOfWork = loanUnitOfWork;
            _userLogRepository = userLogRepository;
            _userManager = userManager;
            FilterType = LoanFilterType.PrincipalBalanceGreaterThanZero;

            CheckBoxLoanSearchGroup = new List<LoanSearchEnumModel>();
            foreach (LoanSearchGroup loanSearchGroup in Enum.GetValues(typeof(LoanSearchGroup)))
            {
                CheckBoxLoanSearchGroup.Add(new LoanSearchEnumModel() { LoanSearchGroup = loanSearchGroup, IsSelected = false });
            }
            CheckBoxLoanSearchGroup.FirstOrDefault(e => e.LoanSearchGroup == LoanSearchGroup.Loan).IsSelected = true;
            CheckBoxLoanSearchGroup.FirstOrDefault(e => e.LoanSearchGroup == LoanSearchGroup.Properties).IsSelected = true;

            AtRiskBeaconScoreThreshold = GetSiteSetting(cache, SiteSettingKey.STRESSTESTATRISKBEACONSCORETHRESHOLD.ToString()).ToString();
            AtRiskLTVThreshold = GetSiteSetting(cache, SiteSettingKey.STRESSTESTATRISKLTVTHRESHOLD.ToString()).ToString();
        }

        public async Task OnGetAsync(string searchFor, LoanFilterType? filterType, DateTime? endDate, List<string> releatedLoanList, List<LoanSearchEnumModel> checkBoxLoanSearchGroup)
        {
            SearchFor = searchFor?.Trim();

            if (filterType != null)
                FilterType = filterType;

            if (filterType == LoanFilterType.Arrears1stMortgages || filterType == LoanFilterType.Arrears2ndMortgages || filterType == LoanFilterType.DelinquentMortgages)
            {
                endDate = DateTime.Today.Date;
            }

            if (endDate != null)
                EndDate = endDate;

            if (checkBoxLoanSearchGroup.Any())
                CheckBoxLoanSearchGroup = checkBoxLoanSearchGroup;
            // If non selected, make loan as default
            if (CheckBoxLoanSearchGroup.All(e => e.IsSelected == false))
            {
                ModelState.Remove("checkBoxLoanSearchGroup[0].IsSelected");
                CheckBoxLoanSearchGroup.FirstOrDefault(e => e.LoanSearchGroup == LoanSearchGroup.Loan).IsSelected = true;
            }

            Loans = await _loanService.GetFilteredLoans(SearchFor, FilterType, CheckBoxLoanSearchGroup, EndDate);

            var currentUser = await _userManager.GetUserAsync(User);
            await _userLogRepository.LogEvent(
                        AreaType.LoanManagement,
                        EventType.GetLoans,
                        currentUser.UserName,
                        $"[Get] Loans: Filter - {FilterType}, Search - {SearchFor}",
                        ResultType.Success
                    );
        }

        public async Task<ActionResult> OnPostSaveNotesAsync(string recID, string loanNotes)
        {
            string message;

            if (!ModelState.IsValid)
            {
                return new JsonResult(new { Result = ResultType.Failure.ToDescription(), Message = "Invalid model state" });
            }

            try
            {
                AppNote originalLoanNote = await ((ISharedUnitOfWork)_loanUnitOfWork).NoteRepository.FindAsync(recID);

                string originalLoanNoteHtml = RtfPipe.Rtf.ToHtml(originalLoanNote.Notes);
                if (!originalLoanNoteHtml.Contains(loanNotes))
                {

                    if (originalLoanNote == null)
                    {
                        originalLoanNote = new AppNote()
                        {
                            RecId = recID,
                        };
                    }

                    HtmlToRtf h = new HtmlToRtf();
                    if (h.OpenHtml(loanNotes))
                    {
                        originalLoanNote.Notes = h.ToRtf();
                    }

                    await ((ISharedUnitOfWork)_loanUnitOfWork).NoteRepository.UpdateAsync(originalLoanNote);

                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        return new JsonResult(new { Result = ResultType.Failure.ToDescription(), Message = $"Unable to load user with ID '{_userManager.GetUserId(User)}'." });
                    }

                    message = "Changes have been updated!";

                    await _userLogRepository.LogEvent(
                                AreaType.LoanManagement,
                                EventType.UpdateNotes,
                                user.UserName,
                                $"[Post] Loan Notes Update - {JsonConvert.SerializeObject(originalLoanNote)}",
                                ResultType.Success
                            );
                }
                else
                {
                    message = "No Changes Detected.";
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }

            return new JsonResult(new { Result = ResultType.Success.ToDescription(), Message = message });
        }

        public bool IsCorrectQualifiedAmount(string stored, decimal calculated)
        {
            string stroedStringVal = String.IsNullOrEmpty(stored) ? "0" : stored;
            return IsCorrectLTV(stroedStringVal.ToDecimal(), calculated);
        }

        public bool IsCorrectLTV(decimal stored, decimal calculated)
        {
            double diff = (double)Math.Abs((Decimal.Round(stored, 2) - Decimal.Round(calculated, 2)));
            return diff < 0.05;
        }
    }
}

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_FullLayout.cshtml
<!DOCTYPE html>
<html lang="en" data-url-prefix="/">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>@ViewBag.Title - Kuber MIC Client Portal</title>
    <meta name="description" content="@ViewBag.Description" />
    <partial name="_Layout.Head" />
</head>
  <body class="h-100">
    <div id="root" class="h-100">
      <!-- Background Start -->
      <div class="fixed-background"></div>
      <!-- Background End -->

      <div class="container-fluid p-0 h-100 position-relative">
        <div class="row g-0 h-100">
            <!-- Left Side Start -->
            <div class="offset-0 col-12 d-none d-lg-flex offset-md-1 col-lg h-lg-100">
            <div class="min-h-100 d-flex align-items-center">
                <div class="w-100 w-lg-75 w-xxl-50">
                    <div>
                        <div class="mb-5">
                            <h1 class="display-3 text-white">Kuber MIC</h1>
                            <h2 class="display-3 text-white">Mortgage Investment Corporation</h2>
                        </div>
                        <p class="h6 text-white lh-1-5 mb-5">
                            Kuber MIC is managed by Square Capital Management inc., a licensed Mortgage Brokerage (Licence #12761) regulated by the Financial Services Regulatory Authority of Ontario and governed by the MBLAA.
                        </p>
                        <div class="mb-5">
                            <a class="btn btn-lg btn-outline-white" href="https://www.kubermic.com/">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <!-- Left Side End -->

            <!-- Right Side Start -->
            <div class="sw-lg-70 min-h-100 bg-foreground d-flex justify-content-center align-items-center shadow-deep py-5 full-page-content-right-border">
                <div class="sw-lg-50 px-5">
                    <!-- Logo Start -->
                    <div class="sh-11">
                        <a asp-page="./login">
                            <img class="frontlogo mb-2" src="/img/logo/kuber-logo-black.svg" alt="logo" />
                            <span class="navbar-brand">&nbsp; MIC Client Portal</span>
                        </a>
                    </div>
                    <!-- Logo End -->

                    @RenderSection("RightSide", required: false)
                </div>
            </div>
            <!-- Right Side End -->
        </div>
      </div>
    </div>
    <partial name="_Layout.Scripts"/>
  </body>
</html>

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_Layout.Breadcrumb.cshtml
@{
    if (ViewBag.Breadcrumbs != null)
    {
        <nav class="breadcrumb-container d-inline-block" aria-label="breadcrumb">
            <ul class="breadcrumb pt-0">
                @foreach (KeyValuePair<string, string> item in ViewBag.Breadcrumbs)
                {
                    <li class="breadcrumb-item"><a asp-page="@item.Key">@item.Value</a></li>
                }
            </ul>
        </nav>
    }
}

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_Layout.Footer.cshtml
<!-- Layout Footer Start -->
<footer>
  <div class="footer-content">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-6">
          <p class="mb-0 text-muted text-medium">Copyright &copy; @(DateTime.Now.Year) - Kuber MIC - Authorized Users Only</p>
        </div>
        <div class="col-sm-6 d-none d-sm-block">
          <ul class="breadcrumb pt-0 pe-0 mb-0 float-end">
            <li class="breadcrumb-item mb-0 text-medium">
              <a href="https://www.kubermic.com" target="_blank" class="btn-link">Kuber MIC</a>
            </li>
            <li class="breadcrumb-item mb-0 text-medium">
              <a href="https://www.squarecapital.ca" target="_blank" class="btn-link">Square Capital</a>
            </li>
            <li class="breadcrumb-item mb-0 text-medium"><a href="https://portal.kubermic.com/" target="_blank" class="btn-link">Kuber Portal</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Layout Footer End -->

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_Layout.Head.cshtml
<!-- Favicon Tags Start -->
<link rel="shortcut icon" href="/img/favicon/favicon.ico" type="image/x-icon">
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/favicon/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/favicon/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/favicon/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/favicon/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="/img/favicon/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/favicon/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/img/favicon/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/favicon/apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="/img/favicon/favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="/img/favicon/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="/img/favicon/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="/img/favicon/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="/img/favicon/favicon-128.png" sizes="128x128" />
<meta name="application-name" content="&nbsp;" />
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="/img/favicon/mstile-144x144.png" />
<meta name="msapplication-square70x70logo" content="/img/favicon/mstile-70x70.png" />
<meta name="msapplication-square150x150logo" content="/img/favicon/mstile-150x150.png" />
<meta name="msapplication-wide310x150logo" content="/img/favicon/mstile-310x150.png" />
<meta name="msapplication-square310x310logo" content="/img/favicon/mstile-310x310.png" />
<!-- Favicon Tags End -->
<!-- Font Tags Start -->
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;700&display=swap" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="/font/CS-Interface/style.css" />
<!-- Font Tags End -->
<!-- Vendor Styles Start -->
<link rel="stylesheet" href="/css/vendor/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css" />
<link rel="stylesheet" href="/css/vendor/OverlayScrollbars.min.css" />
@if (ViewBag.PageStyles != null)
{
    foreach (string filePath in ViewBag.PageStyles)
    {
        <link rel="stylesheet" href="@filePath" />
    }
}
<!-- Vendor Styles End -->
<!-- Template Base Styles Start -->
<link rel="stylesheet" href="/css/styles.css" />
<link rel="stylesheet" href="/css/main.css" />
<!-- Template Base Styles End -->
<script src="/js/base/loader.js"></script>

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_Layout.Nav.cshtml
@inject UserManager<ApplicationUser> UserManager

<div class="nav-content d-flex">
  <!-- Logo Start -->
  <div class="logo position-relative">
    <a asp-page="/Dashboard">
      <!-- Logo can be added directly -->
      <img src="/img/logo/kuber-logo-white.png" alt="logo" />

      <!-- Or added via css to provide different ones for different color themes -->
      @*<div class="img"></div>*@
    </a>
  </div>
  <div class="logo position-relative">
    <a class="navbar-brand text-white" asp-page="/Dashboard">&nbsp; MIC Client Portal</a>
  </div>
  <!-- Logo End -->

  <!-- User Menu Start -->
  <div class="user-container d-flex">
    <a href="#" class="d-flex user position-relative" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="mt-1 me-2 d-inline-block text-white icon-22 bi-person-circle"></i>
      <div class="name">@UserManager.GetUserName(User) </div>
    </a>
    <div class="dropdown-menu dropdown-menu-end user-menu wide">
      <div class="row mb-3 ms-0 me-0">
        <div class="col-12 ps-1 mb-2">
          <div class="text-extra-small text-primary">ACCOUNT</div>
        </div>
        <div class="col-12 ps-1 pe-1">
          <ul class="list-unstyled">
            <li>
              <a asp-area="Identity" asp-page="/Account/Manage/Index" title="My Profile">My Profile</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row mb-1 ms-0 me-0">
        <div class="col-12 p-1 mb-3 pt-3">
          <div class="separator-light"></div>
        </div>
        <div class="col-6 ps-1 pe-1">
          <ul class="list-unstyled">
            <li>
              <a href="https://portal.kubermic.com">
                <i data-acorn-icon="help" class="me-2" data-acorn-size="17"></i>
                <span class="align-middle">Help</span>
              </a>
            </li>
            <li>
              @if (SignInManager.IsSignedIn(User))
              {
                @*<form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/index", new { area = "" })" method="post" id="logoutForm">
                    <button type="submit" class="btn btn-link navbar-btn navbar-link">
                        <i data-acorn-icon="logout" data-acorn-size="17"></i>
                        <span class="align-middle">Logout</span>
                    </button>
                </form>*@
                <a asp-area="Identity" asp-page="/Account/Logout">
                    <i data-acorn-icon="logout" data-acorn-size="17"></i>
                    <span class="align-middle">Logout</span>
                </a>
              }
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- User Menu End -->

  <!-- Menu Start -->
  <div class="menu-container flex-grow-1">
    <ul id="menu" class="menu">
      @if (User.Claims.Any(c => c.Type == "CanViewLoans" && c.Value == "true"))
      {
        <li>
            <a asp-page="/Loans/Index">
                <i data-acorn-icon="home" class="icon" data-acorn-size="18"></i>
                <span class="label">Loans</span>
            </a>
        </li>
      }
      @if (User.Claims.Any(c => c.Type == "CanViewInvestments" && c.Value == "true"))
      {
        <li>
          <a asp-page="/Partners/Index">
            <i data-acorn-icon="money-bag" class="icon" data-acorn-size="18"></i>
            <span class="label">Partners</span>
          </a>
        </li>
      }
    </ul>
  </div>
  <!-- Menu End -->

  <!-- Mobile Buttons Start -->
  <div class="mobile-buttons-container">
    <!-- Scrollspy Mobile Button Start -->
    <a href="#" id="scrollSpyButton" class="spy-button" data-bs-toggle="dropdown">
      <i data-acorn-icon="menu-dropdown"></i>
    </a>
    <!-- Scrollspy Mobile Button End -->

    <!-- Scrollspy Mobile Dropdown Start -->
    <div class="dropdown-menu dropdown-menu-end" id="scrollSpyDropdown"></div>
    <!-- Scrollspy Mobile Dropdown End -->

    <!-- Menu Button Start -->
    <a href="#" id="mobileMenuButton" class="menu-button">
      <i data-acorn-icon="menu"></i>
    </a>
    <!-- Menu Button End -->
  </div>
  <!-- Mobile Buttons End -->
</div>
<div class="nav-shadow"></div>

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_Layout.Scripts.cshtml
<!-- Vendor Scripts Start -->
<script src="/js/vendor/jquery-3.5.1.min.js"></script>
<script src="/js/vendor/bootstrap.bundle.min.js"></script>
<script src="/js/vendor/OverlayScrollbars.min.js"></script>
<script src="/js/vendor/autoComplete.min.js"></script>
<script src="/js/vendor/clamp.min.js"></script>
<script src="/icon/acorn-icons.js"></script>
<script src="/icon/acorn-icons-commerce.js"></script>
<script src="/icon/acorn-icons-interface.js"></script>
@if (ViewBag.VendorScripts != null)
{
    foreach (string filePath in ViewBag.VendorScripts)
    {
        <script src="@filePath"></script>
    }
}
<!-- Vendor Scripts End -->
<!-- Template Base Scripts Start -->
<script src="/js/base/helpers.js"></script>
<script src="/js/base/globals.js"></script>
<script src="/js/base/nav.js"></script>
<script src="/js/base/search.js"></script>
<script src="/js/base/settings.js"></script>
<!-- Template Base Scripts End -->
<!-- Page Specific Scripts Start -->
@if (ViewBag.PageScripts != null)
{
    foreach (string filePath in ViewBag.PageScripts)
    {
        <script src="@filePath"></script>
    }
}
<script src="/js/common.js"></script>
<script src="/js/scripts.js"></script>
<!-- Page Specific Scripts End -->

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_Layout.SearchModal.cshtml
<!-- Search Modal Start -->
<div class="modal fade modal-under-nav modal-search modal-close-out" id="searchPagesModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header border-0 p-0">
        <button type="button" class="btn-close btn btn-icon btn-icon-only btn-foreground" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body ps-5 pe-5 pb-0 border-0">
        <input id="searchPagesInput" class="form-control form-control-xl borderless ps-0 pe-0 mb-1 auto-complete" type="text" autocomplete="off" />
      </div>
      <div class="modal-footer border-top justify-content-start ps-5 pe-5 pb-3 pt-3 border-0">
        <span class="text-alternate d-inline-block m-0 me-3">
          <i data-acorn-icon="arrow-bottom" data-acorn-size="15" class="text-alternate align-middle me-1"></i>
          <span class="align-middle text-medium">Navigate</span>
        </span>
        <span class="text-alternate d-inline-block m-0 me-3">
          <i data-acorn-icon="arrow-bottom-left" data-acorn-size="15" class="text-alternate align-middle me-1"></i>
          <span class="align-middle text-medium">Select</span>
        </span>
      </div>
    </div>
  </div>
</div>
<!-- Search Modal End -->

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_Layout.cshtml
@{
    List<string> HtmlTagData = new List<string>(){};
    if(ViewBag.HtmlTagData!= null){
        @foreach (KeyValuePair<string, string> item in ViewBag.HtmlTagData)
        {
            HtmlTagData.Add($"data-{@item.Key}='{@item.Value}'");
        }
    }

    List<string> CustomNavData = new List<string>(){};
    if(ViewBag.CustomNavData!= null){
        @foreach (KeyValuePair<string, string> item in ViewBag.CustomNavData)
        {
            CustomNavData.Add($"data-{@item.Key}=\"{@item.Value}\"");
        }
    }
}


<!DOCTYPE html>
<html lang="en" data-url-prefix="/" data-footer="true" data-color="light-red" @Html.Raw(String.Join(" ",HtmlTagData))>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>@ViewBag.Title - Kuber MIC Client Portal</title>
    <meta name="description" content="@ViewBag.Description" />
    <partial name="_Layout.Head" />
</head>

<body>
    <div id="root">
        <div id="nav" class="nav-container d-flex" @Html.Raw(String.Join(" ",CustomNavData))>
            <partial name="_Layout.Nav" />
        </div>
        <main>
            @RenderBody()
        </main>
        <partial name="_Layout.Footer" />
    </div>
    <partial name="_Layout.Scripts"/>
</body>
</html>

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_NotesEditPartial.cshtml
<div class="modal modal-right fade" id="EditNotesModel" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog  modal-xl">
        <div class="modal-content">
            <form method="post" id="LoanNotesForm" onsubmit="return false;">
                <div class="modal-header">
                    <h5 class="modal-title">Edit Notes: <span id="accountID"></span></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                @*@await Html.PartialAsync("_StatusMessage", Model.Message)*@

                <div class="modal-body p-0">
                    <div class="card-body editor-container">
                        <div class="html-editor sh-19" id="quillEditor"></div>
                        <input type="hidden" name="recID" id="recID" value="" />
                        <textarea name="loanNotes" id="loanNotes" style="display:none"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" asp-page-handler="SaveNotes" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_PaginationPartial.cshtml
@using KuberMICManager.Core.Domain.ViewModels
@model PaginationViewModel

@{
    string prevDisabled = !Model.Paginated.HasPreviousPage ? "disabled" : "";
    string nextDisabled = !Model.Paginated.HasNextPage ? "disabled" : "";
}

@if (0 < Model.Paginated.PageIndex && Model.Paginated.PageIndex < Model.Paginated.TotalPages)
{
    <div>
        <div>
            <nav aria-label="page navigation">
                <ul class="pagination justify-content-center">

                    <li class="page-item @prevDisabled"><a class="page-link" asp-route-pageIndex="@(Model.Paginated.PageIndex - 1)">Previous</a></li>
                    <li class="page-item @nextDisabled"><a class="page-link" asp-route-pageIndex="@(Model.Paginated.PageIndex + 1)">Next</a></li>

                    @if (Model.Paginated.PageIndex != 1)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-route-pageIndex="@(Math.Max(1, Model.Paginated.PageIndex - Model.MaxPagesToDisplay))">...</a>
                        </li>
                    }

                    @for (int i = Model.Paginated.PageIndex; i <= Model.DisplayUpToPageIndex; i++)
                    {
                        string active = i == Model.Paginated.PageIndex ? "active" : "";

                        <li class="page-item @(active)">
                            <a class="page-link" asp-route-pageIndex="@(i)">@i</a>
                        </li>
                    }

                    @if (Math.Min(Model.DisplayUpToPageIndex + 1, Model.Paginated.TotalPages) < Model.Paginated.TotalPages)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-route-pageIndex="@(Math.Min(Model.DisplayUpToPageIndex + 1, Model.Paginated.TotalPages))">...</a>
                        </li>
                    }

                </ul>
                <div class="pagination justify-content-center">
                    <span>@((Model.Paginated.PageIndex - 1) * Model.Paginated.PageSize + 1) - @(Model.Paginated.TotalCount < Model.Paginated.PageIndex * Model.Paginated.PageSize ? Model.Paginated.TotalCount : Model.Paginated.PageIndex * Model.Paginated.PageSize) of @Model.Paginated.TotalCount record(s)</span>
                </div>
            </nav>
        </div>
    </div>
}
else
{
    <div>
        <div>
            <nav aria-label="page navigation">
                <ul class="pagination justify-content-center">
                    <li>Page @(Model.Paginated.PageIndex) - @Model.Paginated.TotalCount record(s) found</li>
                </ul>
            </nav>
        </div>
    </div>
}

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Shared/_StatusMessage.cshtml
@if (@Model != null)
{
    <div id="message" class="alert alert-success alert-dismissible" role="alert">
@*        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
*@        @Model
    </div>
}