KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/Index.cshtml.cs
using KuberMICManager.Core.Domain.Entities;
using KuberMICManager.Core.Domain.Entities.Identity;
using KuberMICManager.Core.Domain.Interfaces;
using KuberMICManager.Core.Domain.Interfaces.Services;
using KuberMICManager.Core.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using SautinSoft;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static KuberMICManager.Core.Domain.Entities.Application.Common;

namespace KuberMICManager.Client.WebUI.Pages.Loans
{
    [Authorize(Policy = "CanViewLoans")]
    public class IndexModel : PageModel
    {
        private readonly ILoanService _loanService;
        private readonly ILoanUnitOfWork _loanUnitOfWork;
        private readonly IUserLogRepository _userLogRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public IEnumerable<LoanIndexModel> Loans { get; set; }

        public List<LoanSearchEnumModel> CheckBoxLoanSearchGroup { get; set; }
        public string SearchFor { get; set; }
        public LoanFilterType? FilterType { get; set; }
        public DateTime? EndDate { get; set; }
        public string AtRiskBeaconScoreThreshold { get; set; }
        public string AtRiskLTVThreshold { get; set; }

        public IndexModel(ILoanService loanService,
                          ILoanUnitOfWork loanUnitOfWork,
                          IUserLogRepository userLogRepository,
                          UserManager<ApplicationUser> userManager,
                          IMemoryCache cache)
        {
            _loanService = loanService;
            _loanUnitOfWork = loanUnitOfWork;
            _userLogRepository = userLogRepository;
            _userManager = userManager;
            FilterType = LoanFilterType.PrincipalBalanceGreaterThanZero;

            CheckBoxLoanSearchGroup = new List<LoanSearchEnumModel>();
            foreach (LoanSearchGroup loanSearchGroup in Enum.GetValues(typeof(LoanSearchGroup)))
            {
                CheckBoxLoanSearchGroup.Add(new LoanSearchEnumModel() { LoanSearchGroup = loanSearchGroup, IsSelected = false });
            }
            CheckBoxLoanSearchGroup.FirstOrDefault(e => e.LoanSearchGroup == LoanSearchGroup.Loan).IsSelected = true;
            CheckBoxLoanSearchGroup.FirstOrDefault(e => e.LoanSearchGroup == LoanSearchGroup.Properties).IsSelected = true;

            AtRiskBeaconScoreThreshold = GetSiteSetting(cache, SiteSettingKey.STRESSTESTATRISKBEACONSCORETHRESHOLD.ToString()).ToString();
            AtRiskLTVThreshold = GetSiteSetting(cache, SiteSettingKey.STRESSTESTATRISKLTVTHRESHOLD.ToString()).ToString();
        }

        public async Task OnGetAsync(string searchFor, LoanFilterType? filterType, DateTime? endDate, List<string> releatedLoanList, List<LoanSearchEnumModel> checkBoxLoanSearchGroup)
        {
            SearchFor = searchFor?.Trim();

            if (filterType != null)
                FilterType = filterType;

            if (filterType == LoanFilterType.Arrears1stMortgages || filterType == LoanFilterType.Arrears2ndMortgages || filterType == LoanFilterType.DelinquentMortgages)
            {
                endDate = DateTime.Today.Date;
            }

            if (endDate != null)
                EndDate = endDate;

            if (checkBoxLoanSearchGroup.Any())
                CheckBoxLoanSearchGroup = checkBoxLoanSearchGroup;
            // If non selected, make loan as default
            if (CheckBoxLoanSearchGroup.All(e => e.IsSelected == false))
            {
                ModelState.Remove("checkBoxLoanSearchGroup[0].IsSelected");
                CheckBoxLoanSearchGroup.FirstOrDefault(e => e.LoanSearchGroup == LoanSearchGroup.Loan).IsSelected = true;
            }

            Loans = await _loanService.GetFilteredLoans(SearchFor, FilterType, CheckBoxLoanSearchGroup, EndDate);

            var currentUser = await _userManager.GetUserAsync(User);
            await _userLogRepository.LogEvent(
                        AreaType.LoanManagement,
                        EventType.GetLoans,
                        currentUser.UserName,
                        $"[Get] Loans: Filter - {FilterType}, Search - {SearchFor}",
                        ResultType.Success
                    );
        }

        public async Task<ActionResult> OnPostSaveNotesAsync(string recID, string loanNotes)
        {
            string message;

            if (!ModelState.IsValid)
            {
                return new JsonResult(new { Result = ResultType.Failure.ToDescription(), Message = "Invalid model state" });
            }

            try
            {
                AppNote originalLoanNote = await ((ISharedUnitOfWork)_loanUnitOfWork).NoteRepository.FindAsync(recID);

                string originalLoanNoteHtml = RtfPipe.Rtf.ToHtml(originalLoanNote.Notes);
                if (!originalLoanNoteHtml.Contains(loanNotes))
                {

                    if (originalLoanNote == null)
                    {
                        originalLoanNote = new AppNote()
                        {
                            RecId = recID,
                        };
                    }

                    HtmlToRtf h = new HtmlToRtf();
                    if (h.OpenHtml(loanNotes))
                    {
                        originalLoanNote.Notes = h.ToRtf();
                    }

                    await ((ISharedUnitOfWork)_loanUnitOfWork).NoteRepository.UpdateAsync(originalLoanNote);

                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        return new JsonResult(new { Result = ResultType.Failure.ToDescription(), Message = $"Unable to load user with ID '{_userManager.GetUserId(User)}'." });
                    }

                    message = "Changes have been updated!";

                    await _userLogRepository.LogEvent(
                                AreaType.LoanManagement,
                                EventType.UpdateNotes,
                                user.UserName,
                                $"[Post] Loan Notes Update - {JsonConvert.SerializeObject(originalLoanNote)}",
                                ResultType.Success
                            );
                }
                else
                {
                    message = "No Changes Detected.";
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }

            return new JsonResult(new { Result = ResultType.Success.ToDescription(), Message = message });
        }

        public bool IsCorrectQualifiedAmount(string stored, decimal calculated)
        {
            string stroedStringVal = String.IsNullOrEmpty(stored) ? "0" : stored;
            return IsCorrectLTV(stroedStringVal.ToDecimal(), calculated);
        }

        public bool IsCorrectLTV(decimal stored, decimal calculated)
        {
            double diff = (double)Math.Abs((Decimal.Round(stored, 2) - Decimal.Round(calculated, 2)));
            return diff < 0.05;
        }
    }
}

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/ViewLoan.cshtml.cs
using KuberMICManager.Core.Domain.Entities;
using KuberMICManager.Core.Domain.Entities.Identity;
using KuberMICManager.Core.Domain.Interfaces;
using KuberMICManager.Core.Domain.Interfaces.Services;
using KuberMICManager.Core.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using System.Threading.Tasks;
using static KuberMICManager.Core.Domain.Entities.Application.Common;

namespace KuberMICManager.Client.WebUI.Pages.Loans
{
    [Authorize(Policy = "CanViewLoans")]
    public class ViewLoanModel : PageModel
    {
        private readonly IUserLogRepository _userLogRepository;
        private readonly ILoanService _loanService;
        private readonly IGoogleAPISerivce _googleAPIService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ViewLoanModel(IUserLogRepository userLogRepository, 
                             ILoanService loanService,
                             IGoogleAPISerivce googleAPIService,
                             UserManager<ApplicationUser> userManager)
        {
            _userLogRepository = userLogRepository;
            _loanService = loanService;
            _googleAPIService = googleAPIService;
            _userManager = userManager;
        }

        [BindProperty]
        public LoanViewModel LoanViewModel { get; set; }
        public ReturnToPage ReturnToPage { get; set; }

        public async Task<IActionResult> OnGetAsync(string id, ReturnToPage returnToPage = ReturnToPage.LoanList)
        {
            if (id == null)
            {
                return NotFound();
            }

            ReturnToPage = returnToPage;

            LoanViewModel = await _loanService.GetLoanDetailsByIdAsync(id);

            var currentUser = await _userManager.GetUserAsync(User);
            if (LoanViewModel == null)
            {
                await _userLogRepository.LogEvent(
                        AreaType.LoanManagement,
                        EventType.GetLoans,
                        currentUser.UserName,
                        $"View Loan - Loan ID {id}",
                        ResultType.NotFound);

                return NotFound();
            }

            await _userLogRepository.LogEvent(
                        AreaType.LoanManagement,
                        EventType.GetPartners,
                        currentUser.UserName,
                        $"View Loan - Loan ID: {id}, Loan Account: {LoanViewModel.Loan.Account}",
                        ResultType.Success);

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDownloadAsync(string fileName, string fileDescription)
        {
            FileInfo fileInfo = new FileInfo(fileName);

            MemoryStream outputStream = new System.IO.MemoryStream();
            await _googleAPIService.GetGDriveFileByName(fileName, outputStream);

            var currentUser = await _userManager.GetUserAsync(User);
            await _userLogRepository.LogEvent(
                        AreaType.LoanManagement,
                        EventType.GetLoanAttachment,
                        currentUser.UserName,
                        $"View Loan - Attachment Download - File Name: {fileName}, Description: {fileDescription}",
                        outputStream.Length > 0 ? ResultType.Success : ResultType.Failure);

            return File(outputStream.ToArray(), "application/force-download", fileDescription + "." + fileInfo.Extension);
        }

        public decimal? GetTotalAmountReceived(TdsLoanHistory loanHistory)
        {
            return ((loanHistory.ToInterest > 0) ? loanHistory.ToInterest : 0) +
                   ((loanHistory.ToPrincipal > 0) ? loanHistory.ToPrincipal : 0) +
                   ((loanHistory.ToChargesPrin > 0) ? loanHistory.ToChargesPrin : 0);
        }
    }
}

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/ViewLoan.cshtml
@page
@model KuberMICManager.Client.WebUI.Pages.Loans.ViewLoanModel
@{
    Dictionary<string, string> HtmlTagData = new Dictionary<string, string>() { };
    ViewBag.HtmlTagData = HtmlTagData;

    List<string> PageStyles = new List<string>()
    {
        "/css/vendor/datatables.min.css"
    };
    ViewBag.PageStyles = PageStyles;

    List<string> VendorScripts = new List<string>()
    {
        "/js/vendor/datatables.min.js",
    };
    ViewBag.VendorScripts = VendorScripts;

    List<string> PageScripts = new List<string>()
    {
        "/js/cs/datatable.extend.js",
        "/js/plugins/datatable.base.js",
        "/js/plugins/datatable.loan.history.js",
        "/js/plugins/datatable.attachments.js",
        "/js/site.js"
    };
    ViewBag.PageScripts = PageScripts;

    Dictionary<string, string> Breadcrumbs = new Dictionary<string, string>(){
        {"/dashboard","Home"},
        {"/loans/Index","Loans"}
    };
    ViewBag.Breadcrumbs = Breadcrumbs; 

    ViewData["Title"] = "Loan: " + @Model.LoanViewModel.Loan.Account + " - " + @Model.LoanViewModel.Loan.FullName;
    ViewBag.Description = "Loan: " + @Model.LoanViewModel.Loan.Account + " - " + @Model.LoanViewModel.Loan.FullName;
}

<div class="container">
    <div class="row">
        <!-- Title and Top Buttons Start -->
        <div class="page-title-container">
            <div class="row">
                <!-- Title Start -->
                <div class="col-12 col-md-7">
                    <h2 class="mb-2 pb-0 display-6" id="title">@ViewBag.Title</h2>
                    <partial name="_Layout.Breadcrumb"/>
                </div>
                <!-- Title End -->
                <div class="col-12 col-md-5 mt-4 text-end">
                    <a href="@GetReturnLink(Model.ReturnToPage)">
                        <i data-acorn-icon="arrow-double-left" class="icon ql-align-right text-small"></i>Back to List
                    </a>
                </div>
            </div>
        </div>
        <hr />
        <!-- Title and Top Buttons End -->
    </div>

    <div class="row">
        <!-- Left Navigation Start -->
        <div class="col-12 col-xl-2 w-10">
            <!-- Menu Start -->
           <partial name="_Layout.SideNavLoanDetails"/>
            <!-- Menu End -->
       </div>
       <!-- Left Navigation End -->

       <!-- Content End -->
       <div class="col-12 col-xl-10 w-90">
            <!-- Page Content Start -->
            <form class="tooltip-end-top" method="post">
                <partial name="_Loan.Coborrowers" />
                <partial name="_Loan.Terms" />
                <partial name="_Loan.Funding" />
                <partial name="_Loan.Charges" />
                <partial name="_Loan.Properties" />
                <partial name="_Loan.History" />
                <partial name="_Loan.TrustLedger" />
                <partial name="_Loan.Attachments" />
                <partial name="_Loan.CustomFields" />
                <partial name="_Loan.Notes" />
            </form>
            <!-- Page Content End -->
        </div>
        <!-- Content End -->
    </div>

    <div class="row text-end">
        <a href="@GetReturnLink(Model.ReturnToPage)">
            <i data-acorn-icon="arrow-double-left" class="icon ql-align-right text-small"></i>Back to List
        </a>
    </div>
</div>

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/_Layout.SideNavLoanDetails.cshtml
<div class="col-auto side-menu-container">
  <ul class="sw-25 side-menu mb-0 primary" id="sideMenu">
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_borrowers')" class="pb-0">
        <i data-acorn-icon="user" class="icon"></i>
        <span class="label">Borrowers</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_terms')" class="pb-0">
        <i data-acorn-icon="pos" class="icon"></i>
        <span class="label">Terms</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_funding')" class="pb-0">
        <i data-acorn-icon="money-bag" class="icon"></i>
        <span class="label">Funding</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_charges')" class="pb-0">
        <i data-acorn-icon="category" class="icon"></i>
        <span class="label">Charges</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_properties')" class="pb-0">
        <i data-acorn-icon="home" class="icon"></i>
        <span class="label">Properties</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_history')" class="pb-0">
        <i data-acorn-icon="clock" class="icon"></i>
        <span class="label">History</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_trust_ledger')" class="pb-0">
        <i data-acorn-icon="note" class="icon"></i>
        <span class="label">Trust Ledger</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_attachments')" class="pb-0">
        <i data-acorn-icon="attachment" class="icon"></i>
        <span class="label">Attachments</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_custom_fields')" class="pb-0">
        <i data-acorn-icon="form" class="icon"></i>
        <span class="label">Custom Fields</span>
      </a>
    </li>
    <li>
      <a href="#" onclick="SideMenuHandler('section.loan_notes')" class="pb-0">
        <i data-acorn-icon="file-text" class="icon"></i>
        <span class="label">Notes</span>
      </a>
    </li>
  </ul>
</div>

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/_Loan.Attachments.cshtml
@model KuberMICManager.Client.WebUI.Pages.Loans.ViewLoanModel

<!-- Attachments Start -->
<section class="scroll-section loan_attachments">
    <h2 class="small-title">Attachments</h2>
    <!-- Content Start -->
    <div class="data-table-boxed">
        <!-- Controls Start -->
        <div class="row mb-2">
            <!-- Search Start -->
            <div class="col-sm-12 col-md-5 col-lg-3 col-xxl-2 mb-1">
                <div class="d-inline-block float-md-start me-1 mb-1 search-input-container w-100 shadow bg-foreground">
                    <input class="form-control datatable-search" placeholder="Search" data-datatable="#datatableBoxed_Attachments" />
                    <span class="search-magnifier-icon">
                        <i data-acorn-icon="search"></i>
                    </span>
                    <span class="search-delete-icon d-none">
                        <i data-acorn-icon="close"></i>
                    </span>
                </div>
            </div>
            <!-- Search End -->
            <div class="col-sm-12 col-md-7 col-lg-9 col-xxl-10 text-end mb-1">
                <div class="d-inline-block me-0 me-sm-3 float-start float-md-none">
                    <!-- Export Start -->
                    <button class="btn btn-icon btn-icon-only btn-foreground-alternate shadow datatable-export"
                            data-bs-delay="0"
                            data-datatable="#datatableBoxed_Attachments"
                            data-bs-toggle="tooltip"
                            data-bs-placement="top"
                            title="Export"
                            type="button">
                        <i data-acorn-icon="download"></i>
                    </button>
                    <!-- Export End -->
                    <!-- Length Start -->
                    <div class="dropdown-as-select d-inline-block datatable-length" data-datatable="#datatableBoxed_Attachments" data-childSelector="span">
                        <input id="DataTableTotalCount" name="DataTableTotalCount" type="hidden" value="@Model.LoanViewModel.Attachments.Count()" />
                        <button class="btn p-0 shadow" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-bs-offset="0,3">
                            <span class="btn btn-foreground-alternate dropdown-toggle"
                                  data-bs-toggle="tooltip"
                                  data-bs-placement="top"
                                  data-bs-delay="0"
                                  title="Item Count">
                                25 Items
                            </span>
                        </button>
                        <div class="dropdown-menu shadow dropdown-menu-end">
                            @{
                                if (@Model.LoanViewModel.Attachments.Count() > 10)
                                {
                                    <a class="dropdown-item" href="#">10 Items</a>
                                }
                                if (@Model.LoanViewModel.Attachments.Count() > 50)
                                {
                                    <a class="dropdown-item" href="#">25 Items</a>
                                }
                                if (@Model.LoanViewModel.Attachments.Count() > 50)
                                {
                                    <a class="dropdown-item" href="#">50 Items</a>
                                }
                                if (@Model.LoanViewModel.Attachments.Count() > 100)
                                {
                                    <a class="dropdown-item" href="#">100 Items</a>
                                }
                            }
                            <a class="dropdown-item active" href="#">All Items</a>
                        </div>
                    </div>
                    <!-- Length End -->
                </div>
            </div>
        </div>
        <!-- Controls End -->
        <!-- Table Start -->
        <div>
            <table id="datatableBoxed_Attachments" class="stripe data-table nowrap hover">
                <thead>
                    <tr role="row">
                        <th class="text-muted text-medium text-uppercase">DESCRIPTION</th>
                        <th class="text-muted text-medium text-uppercase">ADDED</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int index = 0;
                        foreach (var attachment in Model.LoanViewModel.Attachments?.OrderByDescending(l => l.SysCreatedDate))
                        {
                            <tr role="row" class="@((index++ % 2 == 0) ? "odd" : "even")">
                                <td>
                                    <button type="submit"
                                    class="btn btn-link p-0"
                                    asp-page-handler="download"
                                    asp-route-filename="@attachment.FileName"
                                    asp-route-filedescription="@attachment.Description">
                                        <i class="fa fa-download"></i>@attachment.Description
                                    </button>
                                </td>
                                <td>@String.Format("{0:MM/dd/yyyy h:mm tt}",attachment.SysCreatedDate)</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <!-- Table End -->
    </div>
    <!-- Content End -->
</section>
<!-- Attachments End -->

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/_Loan.Charges.cshtml
@model KuberMICManager.Client.WebUI.Pages.Loans.ViewLoanModel

<!-- Charges Start -->
<section class="scroll-section loan_charges">
    <h2 class="small-title">Charges</h2>
    <div class="row">
        <div class="col-12 col-xl-12">
            <div class="card mb-5">
                <div class="card-body">
                    <div class="dataTables_wrapper">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="table-container">
                                    <table class="stripe dataTable">
                                        <thead>
                                            <tr role="row">
                                                <th class="text-muted text-medium text-uppercase">DATE</th>
                                                <th class="text-muted text-medium text-uppercase">DESCRIPTION</th>
                                                <th class="text-muted text-medium text-uppercase text-end">INTEREST RATE</th>
                                                <th class="text-muted text-medium text-uppercase text-end">INTEREST FROM</th>
                                                <th class="text-muted text-medium text-uppercase text-center" style="width:120px">DEFERRED</th>
                                                <th class="text-muted text-medium text-uppercase text-end">OWED TO ACCOUNT</th>
                                                <th class="text-muted text-medium text-uppercase text-end">ORIGINAL BALANCE</th>
                                                <th class="text-muted text-medium text-uppercase text-end">UNPAID BALANCE</th>
                                                <th class="text-muted text-medium text-uppercase text-end">ACCRUED INTEREST</th>
                                                <th class="text-muted text-medium text-uppercase text-end">TOTAL DUE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                int index = 0;
                                                foreach (var charge in Model.LoanViewModel.Charges?.OrderBy(c => c.ChargeDate))
                                                {
                                                    <tr role="row" class="@((index++ % 2 == 0) ? "odd" : "even")">
                                                        <td>@String.Format("{0:MM/dd/yyyy}",charge.ChargeDate)</td>
                                                        <td>@charge.Description</td>
                                                        <td class="text-end">@String.Format("{0:n2}", charge.IntRate)%</td>
                                                        <td class="text-end">@String.Format("{0:MM/dd/yyyy}",charge.IntFrom)</td>
                                                        <td class="text-center">
                                                            @if(charge.Deferred == true)
                                                            {
                                                                <label class="form-check w-100 mt-0 text-center">
                                                                    <input type="checkbox" class="form-check-input mt-2" checked="@(charge.Deferred == true)" disabled/>
                                                                </label>
                                                            }
                                                        </td>
                                                        <td class="text-end">@*$@String.Format("{0:n2}", charge.OwedToRecId)*@</td>
                                                        <td class="text-end">$@String.Format("{0:n2}", charge.OrigAmt)</td>
                                                        <td class="text-end">$@String.Format("{0:n2}", charge.OwedToBal)</td>
                                                        <td class="text-end">
                                                            @{
                                                                Decimal interest = 0;
                                                                if(charge.IntFrom != null)
                                                                {
                                                                    interest = (Decimal)((TimeSpan)(charge.IntFrom - DateTime.Today)).TotalDays * (Decimal)(charge.IntRate / 365);
                                                                }
                                                                <label class="">$@String.Format("{0:n2}", interest)</label>
                                                            }
                                                        </td>
                                                        <td class="text-end">
                                                            @{
                                                                var total = charge.OwedToBal;
                                                                if(charge.IntFrom != null)
                                                                {
                                                                    total += (Decimal)((TimeSpan)(charge.IntFrom - DateTime.Today)).TotalDays * (charge.IntRate / 365);
                                                                }
                                                                <label class="">$@String.Format("{0:n2}", total)</label>
                                                            }
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>                                      
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Charges End -->

KuberMICCustomerPortal/KuberMICCustomerPortal/Source/KuberMICManager.Client.ClientPortal/Pages/Loans/_Loan.Notes.cshtml
@model KuberMICManager.Client.WebUI.Pages.Loans.ViewLoanModel
@using KuberMICManager.Core.Domain.Entities.Application

<!-- Notes Start -->
<section class="scroll-section loan_notes">
    <h2 class="small-title">Notes</h2>
    <div class="row">
        <div class="col-12 col-xl-12">
            <div class="card mb-5">
                <div class="card-body">
                    <div class="row g-3">
                        <div class="col-md-12">
                            @Html.Raw(RtfPipe.Rtf.ToHtml(Model.LoanViewModel.Notes?.Notes))
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Notes End -->